spring:
   profiles:
      active:
       - dev
---             #类似于分隔符
server: 
  port: 7001
  context-path: /
spring:
   profiles: dev
   application:
    name: springcloud-zzg-microsoftservices-config-eureka-client
eureka: 
  instance:
    hostname: client-config-eureka7001.com     #eureka服务端的实例名称
#  client: 
#    register-with-eureka: false     #false表示不向注册中心注册自己。
#    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
---             #类似于分隔符
server: 
  port: 7005
  context-path: /
spring:
   profiles: test
   application:
    name: springcloud-zzg-microsoftservices-config-eureka-client
eureka: 
  instance:
    hostname: client-config-eureka7005.com    #eureka服务端的实例名称
#  client: 
#    register-with-eureka: false     #false表示不向注册中心注册自己。
#    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务      
 

 